#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart File
sh /$HOME/.config/bspwm/autostart


bspc monitor -d I II III IV V VI VII VIII IX X

#
# Decor
#
bspc config border_radius        12
bspc config border_width         3
bspc config window_gap          12

#
# Colors
#

# Gruvbox-Dark-Hard
bspc config focused_border_color \#FAF5D7

# Dracula
# bspc config focused_border_color \#BD93F9

# Red
# bspc config normal_border_color \#191919

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#
# Rules
# 

# bspc rule -a is used to create rules
# Example: bspc rule -a Gimp desktop='^8' state=floating follow=on focus=off
# See more at https://github.com/baskerville/bspwm/wiki/Command-Syntax-Rewrite#rule-command

# bspc rule -a brave desktop=^9 
